server.port=8080

# Loga SMS SDK - Default configuration
loga.api.sms-messaging.meteor.oauth2.token-url=https://api.sms.loga-apps.com/oauth/v1/token
loga.api.sms-meteor.oauth2.grant-type=client_credentials
loga.api.sms-messaging.meteor.oauth2.client-id=${LOGA_SMS_CLIENT_ID}
loga.api.sms-messaging.meteor.oauth2.client-secret=${LOGA_SMS_CLIENT_SECRET}
loga.api.sms-messaging.meteor.oauth2.api-key=${LOGA_SMS_API_KEY}
loga.api.sms-messaging.meteor.restclient.api-base-url=https://api.sms.loga-apps.com
loga.api.sms-messaging.meteor.restclient.callback-url=https://mon-app.com/webhook/sms-status
loga.api.sms-messaging.meteor.default-sender-name=MonAppSpring
